### ISSUE TITLE
Get Callstack has null linenumber for top frame

### ISSUE THREAD

**Issue by ursmanoj** [swojtasiak/jsrdbg#19]
Reproduction steps:
- Put a breakpoint anywhere, make sure code snippet is callee to a function
- When breakpoint is hit, 'step into' the another function
- get_stacktrace

Issue: {"url":"example.js","line":null,"rDepth":0}, null linenumber for top frame.

**Comment by swojtasiak** [comment]
Thanks for reporting it, I'll take a look at it in the near future.

**Comment by swojtasiak** [comment]
fixed, thanks
