### ISSUE TITLE
[Query] get_variables: is there a way to know maximum depth variables

### ISSUE THREAD

**Issue by ursmanoj** [swojtasiak/jsrdbg#20]
Is there a direct way to know maximum depth of nested variables in given strack frame?

One way I understand is to repeatedly do get_variables, until there is no further variable field to be expanded, but the method needs multiple interactions with JSRDBG over TCP.
Any single interaction method, which I could not figure out?

Thanks in advance.
Manoj

**Comment by swojtasiak** [comment]
Hi, unfortunately there is no direct way to do that at the moment. 

You will find implementation of this operation here:

https://github.com/swojtasiak/jsrdbg/blob/3de305d7d0ed61225c30581c2d3ae4f66d63e61a/src/js/mozjs_dbg.js#L933

It uses object walker which is responsible for expanding objects:

https://github.com/swojtasiak/jsrdbg/blob/3de305d7d0ed61225c30581c2d3ae4f66d63e61a/src/js/mozjs_dbg.js#L236
